# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
app = " "
primary_region = " "

kill_signal = "SIGTERM"
kill_timeout = 300

[env]
  QDRANT__SERVICE__HOST= "::"
  QDRANT__CLUSTER__ENABLED = "true"
  QDRANT__STORAGE__SNAPSHOTS_PATH = "/data/qdrant/snapshots"
  QDRANT__STORAGE__STORAGE_PATH = "/data/qdrant/storage"

[[mounts]]
  source = "qdrant_data"
  destination = "/data"

# Expose 6333 and 6334 so that we can use Flycast in client apps

[[services]]
  internal_port = 6333
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 3

  [[services.ports]]
    handlers = ["http"]
    port = 6333

  [[services.tcp_checks]]
    interval = "15s"
    grace_period = "10s"
    restart_limit = 0

[[services]]
  protocol = "tcp"
  internal_port = 6334

  [[services.ports]]
    handlers = []
    port = 6334
    tls_options = { "alpn" = ["h2"] }
  
  [[services.tcp_checks]]
    interval = "15s"
    grace_period = "10s"
    restart_limit = 0

[metrics]
  port = 6333
  path = "/metrics"
